# Generated by Django 4.2.4 on 2023-08-17 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_remove_room_usrname_message_room_message_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='Name',
            new_name='name',
        ),
    ]
